# Generated by Django 4.0.6 on 2022-08-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_currency_thirdparty_wallet_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='Symbol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
